const images = {
    Editorial: [
        { brand: "Perfect Magazine", count: 4 },
        { brand: "Pop Magazine", count: 2 },
        { brand: "W Magazine", count: 2 },
        { brand: "D Rep", count: 6 },
        { brand: "Re-Edition Magazine", count: 2 },
        { brand: "Vogue", count: 12 },
        { brand: "10 Magazine", count: 7 },
        { brand: "The Telegraph", count: 4},
        { brand: "GQ", count: 4 },
        { brand: "Portrait Magazine", count: 3 },
        { brand: "Dazed&Confused Magazine", count: 2 },
        { brand: "Revue Magazine", count: 1 },
        { brand: "Tide Magazine", count: 2 },
        { brand: "Alla Carta", count: 3 },
        { brand: "Vanity Fair", count: 4 },
        { brand: "Monrowe Magazine", count: 2 },
        { brand: "Madame Figaro", count: 1 },
        { brand: "Dapper Dan Magazine", count: 1 },
        { brand: "Harper Bazaar", count: 1 },
        { brand: "Elle", count: 1 },
        { brand: "The Plant Magazine", count: 4 },
        { brand: "Epoch Magazine", count: 2 },
        { brand: "Amica", count: 2 },
        { brand: "Alei Journal", count: 2 },
    

        
    ],
    Commercial: [
        { brand: "Heineken", count: 3 },
        { brand: "Anderson Bell", count: 1 },
        { brand: "Prada", count: 5 },
        { brand: "Balenciaga", count: 1 },
        { brand: "Moncler", count: 5 },
        { brand: "Dolce&Gabbana", count: 9 },
        { brand: "Off White", count: 2 },
        { brand: "Puma", count: 1 },
        { brand: "Moon Boot", count: 1 },
        { brand: "Gucci", count: 2 },
        { brand: "Priscavera", count: 4 },
        { brand: "Simona Vanth", count: 1 },
        { brand: "Isabel Marant", count: 2 },
        { brand: "Sunnei", count: 3 },
        { brand: "Armani", count: 9 },
        { brand: "Kenzo", count: 2 },
        { brand: "Cartier", count: 1 },
        { brand: "David Beckham", count: 1 },
        { brand: "Cesare Paciotti", count: 1 },
        { brand: "Roger Vivier", count: 2 },
        { brand: "Zara", count: 2 },
        { brand: "Bulgari", count: 3 },
        { brand: "MSGM", count: 2 },
        { brand: "Mulberry", count: 1 },
        { brand: "Bershka", count: 1 },
        { brand: "Diesel", count: 6 },
        { brand: "The Attico", count: 2 },
        { brand: "Versace", count: 2 },
        { brand: "Tom Ford", count: 2 },
        { brand: "K-Way", count: 1 },
        { brand: "Pucci", count: 4 },
        { brand: "Tod's", count: 1 },
        { brand: "Napapijri", count: 1 },
        { brand: "Pomellato", count: 2 },
        { brand: "Le Monde", count: 3 },
        { brand: "Marni", count: 1 },
        { brand: "Schutz", count: 2 },
        { brand: "Moynat", count: 2 },
        { brand: "Ssense", count: 2 },
        { brand: "Valentino", count: 5 },

        
    ],
    Still: [
        {brand: "Acne Studios", count: 2},
        {brand: "Atkinson", count: 1 },
        {brand: "Bally", count: 2 },
        {brand: "Dedar", count: 2 },
        {brand: "Élitis", count: 2 },
        {brand: "Ferragamo", count: 3 },
        {brand: "Flos", count: 2 },
        {brand: "Lavastone", count: 2 },
        {brand: "Moët&Chandon", count: 1 },
        {brand: "Porada", count: 2 },
        {brand: "Rimowa", count: 4 },
        {brand: "USM", count: 2 },
        {brand: "Yves Saint Laurent", count: 2 },
        {brand: "Burberry", count: 2 },
        {brand: "Hugo Boss", count: 1 },
        {brand: "Brioni", count: 1 },
        {brand: "Trussardi", count: 2 },
        {brand: "De Sede x Pin-Up", count: 4 },
    ]
}

export default images;